### PR TITLE
Community View: Participate tab and contents for Participate pages

### LINKED ISSUE #93: Add tab functionality - Community View Tabs "Agenda" and "Participate"
Add tab functionality - Community View Tabs "Agenda" and "Participate"
Screen Shot 2020-12-15 at 7 08 26 PM

### LINKED ISSUE #94: Implement the contents of the "Participate" tab
Implement the contents of the "Participate" tab
Screen Shot 2020-12-15 at 7 08 26 PM

Screen Shot 2020-12-15 at 7 12 57 PM
Screen Shot 2020-12-15 at 7 12 52 PM
Screen Shot 2020-12-15 at 7 12 47 PM
Screen Shot 2020-12-15 at 7 12 43 PM

### PR DESCRIPTION
**Pull request by terchiem**
### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
  - This PR adds the "Participate" tab toggle in the community member meeting view and adds the contents of the different "Participate" pages. 
  - Closes #93, closes #94.

- Describe what changes are being made
  - `MeetingView` now has a toggle that now switches between displaying the `AgendaView` or `ParticipateView` components
  - The `ParticipateView` component is made to display links to different Participate pages
  - Implemented the contents of each Participate page as its own component
  - Routes were added to `index.js` to display the different Participate pages (suggestions for different route paths welcome!)
    - `participate/join` -> `ParticipateJoin.jsx`
    - `participate/watch` -> `ParticipateWatch.jsx`
    - `participate/comment` -> `ParticipateComment.jsx`
    - `participate/request` -> `ParticipateRequest.jsx`
  - The `Search` component is moved from the `Header` down into the `AgendaView`
  - Components that previously had the `MeetingAgenda` prefix are renamed to just `Agenda`
  - The `/` route now shows a placeholder `MeetingList` component and the `MeetingView` now lives on the `meeting/:id` route

- Describe why these changes are being made
  - The additions of the Participate components were made to address issues #93 and #94 
  - The `Search` component was moved to match the updated [mocks](https://xd.adobe.com/view/5623ff8a-ecc9-47b2-84fd-7826e1fc4c64-0370/screen/06449cf7-f724-43d3-bb9e-430691f5399c)
  - The renaming of the `MeetingAgenda` prefixed components was to simplify and make it easier to tell which components belonged to the `AgendaView` vs the `ParticipateView`
  - The `MeetingView` previously wasn't on a route that had the meeting id which is needed. There was also no way for the user to see a list of meetings, so a placeholder was made on the `/` route and an issue created

- Describe any external libraries/dependencies added or removed in this PR
  - None

- Describe any security risks are there regarding this change
  - Links to external sites
  - Email `mailto` links

- Describe how you tested these changes
  - Visited each route to ensure that the correct components are being displayed
  - Clicked on each external link to ensure that they lead to the correct location and open in a new tab

--------------------------
### :clipboard: Mandatory Checklist
- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
#### Before
Mobile Meeting View
Screen Shot 2021-01-06 at 1 58 23 PM

#### After
Mobile Meeting View with Agenda/Participate Tab
Screen Shot 2021-01-06 at 1 57 25 PM
Mobile Participate View
Screen Shot 2021-01-05 at 1 55 05 PM
ParticipateJoin
Screen Shot 2021-01-05 at 1 55 15 PM
ParticipateWatch
Screen Shot 2021-01-05 at 1 55 29 PM
ParticipateComment
Screen Shot 2021-01-05 at 1 55 45 PM
ParticipateRequest
Screen Shot 2021-01-05 at 1 55 54 PM

--------------------------
### :blue_book: Glossary
- PR = Pull Request

### CODE REVIEW

**Comment by jeffersonken19** [comment]
Decisions: 

add unique meetings id to the route when viewing a meeting (as a community member) that way the back button in the browser will work as expected

make sure the youtube link opens a new tab

The Youtube & City Website links can be static for now and we can make them dynamic in the future.

**Comment by jeffersonken19** [comment]
Open Question: is the eComment link static of dynamic per meeting?

**Review by forkitupforkitup — DISMISSED** [review]
looks good to me

**Review by sepsol — CHANGES_REQUESTED** [review]
It's all good to me but I have two concerns with the back chevron bar:
1. back chevron bar is not the same height as the navbar
2. back chevron bar is not sticky and does not behave the same as the navbar

**Review by JMStudiosJoe — APPROVED** [review]
wonderful work thank you!

**Review by anna-kartynnik — DISMISSED** [review]
Looks good to me but please resolve conflict

**Comment by terchiem** [comment]
Merged latest from `master` and adjusted the back navigation to make it sticky and match the navbar height.

**Review by JMStudiosJoe — APPROVED** [review]

**Pull request merged**
