### PR TITLE
Subscription page: new style + backend integration

### LINKED ISSUE #72: Style community member view subscribe page
Find the full mocks here:
https://docs.google.com/document/d/1bsBU2OwlY0_BJ48z_6H8GPl-vv0a86lvGEPuGZqgvGo/edit#

Screen Shot 2020-11-19 at 9 04 35 PM

### PR DESCRIPTION
**Pull request by anna-kartynnik**
- [x] Fix eslint warnings

Fixes #72 and #91.

### CODE REVIEW

**Comment by jeffersonken19** [comment]
Please attach screenshots / screen recordings + error handling as well

**Comment by forkitupforkitup** [comment]
> * [ ]  Wait until PR#75 is merged to use CustomCheckbox from there.
> * [ ]  Fix eslint warnings
Just as an update @anna-kartynnik, I've merged master into my own branch to integrate with the backend. CustomCheckbox should be done.

**Comment by anna-kartynnik** [comment]
Resolves issues #72 and #91. Preview:


https://user-images.githubusercontent.com/15210801/104410580-847b0780-551d-11eb-9f96-9cc850a15c4e.mov

Note: there are no changes for the state when subscription needs to be confirmed (#92).

**Review by forkitupforkitup — APPROVED** [review]
looks good to me

**Review by JMStudiosJoe — APPROVED** [review]

**Pull request merged**
