### PR TITLE
Issue181

### PR DESCRIPTION
**Pull request by jerrycyip**
### :scroll: Description

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
Fix horizontal scroll on home page

- Describe what changes are being made
added line of css styling to footer component as follows :  box-sizing: border-box

- Describe why these changes are being made
homepage shouldn't display horizontal scroll as content of page is not required/per design.

- List the use cases and edge cases relevant to this PR
n/a  To my knowledge should not affect other use cases/edge cases.  It's a small change, however this is my first PR so hopefully not missing something = )

- Describe how errors will be handled. How will we know if this code breaks in production
Horizontal scroll re-appears even though content of homepage does not spill over horizontally

- Describe any external libraries/dependencies added or removed in this PR
n/a 

- Describe any security risks are there regarding this change
n/a one line of css styling change only.

- Describe how you tested these changes
tested on local environment to confirm horizontal scroll is removed while other functionality appears to be retained.

- Link to relevant external documentation
n/a 

--------------------------
### :clipboard: Mandatory Checklist

- [x] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [x] Have you discussed these changes with the project leader(s)?
- [x] Do all variable and function names communicate what they do?
- [x] Were all the changes commented and / or documented?
- [x] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [x] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [x] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
#### Before
already included with creation of this issue

#### After
Screen Shot 2021-06-15 at 5 14 52 PM

--------------------------
### :blue_book: Glossary
- PR = Pull Request

### CODE REVIEW

**Comment by jerrycyip** [comment]
here's before image:
Screen Shot 2021-06-15 at 5 17 30 PM

**Comment by jerrycyip** [comment]
just a heads up: will be making a pull request for separate issue 223 soon which in part depends on this issue to display properly.  I can make an independent branch for issue 223 for now, but for testing purposes, just wanted to note that a horizontal scroll will still show there until this PR is approved and merged.

**Review by anna-kartynnik — CHANGES_REQUESTED** [review]
@jerrycyip nice work with your first PR! One minor thing: could you please only commit the files that make the change? In this case it's just a one-line change, but when I look at this PR, I can see that it removes more than 1000 lines:
Screen Shot 2021-06-21 at 12 31 30 PM
This is suspicious. If you think that any other files except `frontend/src/components/Footer/Footer.scss` should be changed, please do it in a separate PR where you can describe the motivation why we should do that.

**Comment by jerrycyip** [comment]
lol - whoops!  thanks for the heads up!  sorry, let me redo the commit

**Comment by jerrycyip** [comment]
As per last exchange, I re-baselined my codebase to latest upstream version and then only committed/pushed the one scss file that was changed.  Sorry for the hassle and thanks for reviewing!

**Review by anna-kartynnik — APPROVED** [review]

**Review by terchiem — APPROVED** [review]

**Pull request merged**
