### PR TITLE
Ic/admin table

### PR DESCRIPTION
**Pull request by ppelayo1**
### :scroll: Description

  I was asked by Ian to implement feature.

- Describe the general shape of this PR (new feature? refactor? bug fix? one-line change?)
  Implemented DND kit for support in sorting agenda items
  Agenda View was updated to support swapping between agenda groups
  Meeting View was updated to have each individual meeting item to have a unique id for DND kit to support swapping 
  between containers

- Describe what changes are being made
Removed the old sort method and implemented DND kit. Made the agenda items sortable within their group and between groups. Also had to implement a min height on open agenda groups. This can be changed by editing an option variable. This was necessary in the event that the agenda group is empty. The agenda item being dragged from another agenda group container needs that height to latch onto.

- Describe why these changes are being made
To provide the ability to sort agenda items between groups.

- List the use cases and edge cases relevant to this PR
Use case would be for the moving of agenda items from one group to another, or between the same group.
Edge case would be large number of agenda items and groups, as well as quickly moving agenda items between groups open and closed. 

- Describe how errors will be handled. How will we know if this code breaks in production

- Describe any external libraries/dependencies added or removed in this PR
Added dnd-kit/core and dnd-kit/sortable

- Describe any security risks are there regarding this change

- Describe how you tested these changes
I moved the items around manually between groups. Tested with and without "show completed items" checked. Made sure to move between containers, fill containers with all items. Move items back.

Had unreproducible problem where sometimes a agenda group is empty, and I try to move an agenda item from below that group to the group above quickly and it causes a "Maximum update depth exceeded." error to occur. This error is not easy to reproduce and I included a screenshot of the error page.

- Link to relevant external documentation
https://dndkit.com/

--------------------------
### :clipboard: Mandatory Checklist

- [ ] Linked to the Github Issues being addressed using the right sidebar :arrow_right:
- [ ] Have you discussed these changes with the project leader(s)?
- [ ] Do all variable and function names communicate what they do?
- [ ] Were all the changes commented and / or documented?
- [ ] Is the PR the right size? (If the PR is too large to review, it might be good to break it up into multiple PRs.)
- [ ] Does all work in progress, temporary, or debugger code have a TODO comment with links to Github issues?
- [ ] *If you changed the user interface, did you add before and after screenshots to below?*

--------------------------
#### error screenshot
screencapture-localhost-3000-meeting-1-2021-04-06-13_30_27

--------------------------
### :blue_book: Glossary
- PR = Pull Request

### CODE REVIEW

**Comment by ppelayo1** [comment]
I am new to contributing to projects thru GitHub so let me know anything I am doing incorrectly.

**Review by JMStudiosJoe — APPROVED** [review]
love the comments as well very good clean code great work!

**Comment by anna-kartynnik** [comment]
There is again a problem with `package-lock.json`. It is in every commit. Here there are additions to it but also 23875 deletions. If it's possible, I'd change the file to have only the changes introduced by addition of the new dependencies.

**Comment by anna-kartynnik** [comment]
@ppelayo1 do you want to merge into `codeforsanjose:ic/admin-table` or `develop` branch (you can choose the target branch when you create a pull request if I'm not mistaken)?

**Review by anna-kartynnik — CHANGES_REQUESTED** [review]
Actually, I can't see some code in AgendaView component which should be there. It seems you created your branch on top of `ic/admin-table` which is
> 9 commits ahead, 139 commits behind main

Could you please update to incorporate the latest version of the changed components?

**Comment by ppelayo1** [comment]
I am happy to make the needed changes. I am new to contributing to projects so I will need some help getting pointed the right direction.

Do I need to implement the sorting feature to the agenda components that are in the **main branch** or ""develop branch""? 
Currently both are identical.
Is the problem that since I used "ic/admin-table" branch I implemented the sorter to outdated components?

Using the components from the main branch I get **"Error! Failed to fetch"** at "http://localhost:3000/". 

Am I going to have to manually create dummy data for the MeetingView component so that I have something to work with?

Or is there an easier way to populate the data so that I have something to work with?

**Comment by anna-kartynnik** [comment]
> Do I need to implement the sorting feature to the agenda components that are in the main branch or ""develop branch""?
Currently both are identical.

Starting from today, you can use `develop` branch.

> Is the problem that since I used "ic/admin-table" branch I implemented the sorter to outdated components?

Yes, exactly. There are changes in the components you changed (fetching the data from the server, in particular) that will be overwritten if we merge this version.

> Using the components from the main branch I get "Error! Failed to fetch" at "http://localhost:3000/".

This is strange, not sure if it happens because there is no data in your local db. I don't have such an error. Do you use `docker-compose ...` command to run the project?

> Am I going to have to manually create dummy data for the MeetingView component so that I have something to work with?Or is there an easier way to populate the data so that I have something to work with?

In general, yes, you will need to create some data in your local db. The easiest way is to upload CSV (as shown in PR #173) but it will be available after the PR is merged. I personally use GraphQL Playground (open http://localhost:3000 in the browser) to create some meetings and agenda items (ping me in slack if you need queries template for them).

**Comment by ppelayo1** [comment]
Thank you for the quick reply and the answers.
You are correct the problem is I never bothered to implement the backend. I will get the backend working tomorrow and begin working on adding the sorting features.

Thanks again.

**Comment by JMStudiosJoe** [comment]
Is this PR still a WIP (work in progress) ?

**Comment by ppelayo1** [comment]
Yeah it is, I literally just finished implementing it for the develop branch. Going to clean up the code, and document before I update my branch for the pull request.

**Comment by ppelayo1** [comment]
I am closing this pull request as I opened Drag and Droppable #128 to replace this one.

**Pull request closed without merging**
