### PR TITLE
Restyled community view header (issue 59).

### LINKED ISSUE #59: Community View: Newly styled header
Please implement this new header:
Screen Shot 2020-11-11 at 5 35 34 PM

Full mocks here:
https://xd.adobe.com/view/cbf7839a-5a0e-4771-9915-df00f86156af-9ea4/screen/2ce9cc83-229b-4cd3-8e41-0d9d244c7c95/

### PR DESCRIPTION
**Pull request by anna-kartynnik**
## Description
- [x] Restyles the community view header
- [x] Makes header non-sticky

## Related Issue
Closes #59 

## Screenshot

Screen Shot 2020-11-19 at 8 31 26 PM

### CODE REVIEW

**Comment by jeffersonken19** [comment]
LGTM

**Review by forkitupforkitup — COMMENTED** [review]
Ok

**Review by forkitupforkitup — APPROVED** [review]

**Review by terchiem — APPROVED** [review]
Looks good! There is a small issue with the search bar since the header is no longer sticky:
search

Maybe that can be a separate issue. Great work!

**Review by sepsol — APPROVED** [review]

**Comment by anna-kartynnik** [comment]
@terchiem I fixed search suggestions position in 3c46260.

I also added some basic styling to the search suggestions but I haven't found specific mocks for them, so I feel that the work with search should be made in a separate issue.

**Pull request merged**
