### PR TITLE
Deprecate lambda

### PR DESCRIPTION
**Pull request by sent-hil**
Deprecate lambda and infrastructure related things.

Relies on https://github.com/codeforsanjose/gov-agenda-notifier/pull/178

### CODE REVIEW

**Comment by JMStudiosJoe** [comment]
Are we sure we want to do this still @sent-hil @jeffersonken19 ?

**Comment by sent-hil** [comment]
@JMStudiosJoe let me get confirmation in the next meeting.

**Comment by sent-hil** [comment]
@JMStudiosJoe got confirmation from annie, we're good to go on this

**Comment by jeffersonken19** [comment]
Giving the official go ahead on this work

**Comment by JMStudiosJoe** [comment]
Is this ready to be merged or needs the other wip pr first?

**Comment by sent-hil** [comment]
@JMStudiosJoe this can be merged without the wip

**Pull request merged**
